name: Build Unity Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Armeria-StandaloneWindows64
          restore-keys: |
             Library-Armeria-
             Library-

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - name: Deploy to Steam
        uses: game-ci/steam-deploy@v3
        with:
          username: ethryx
          configVdf: ${{ secrets.CONFIG_VDF}}          
          appId: 2960740
          buildDescription: ${{ github.sha }}
          rootPath: build
          depot1Path: StandaloneWindows64
          releaseBranch: nightly